---
- name: Configure Web Server
  hosts: instance2
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy HTML File to Apache2
      copy:
        src: index.html  # Using Relative Path
        dest: /var/www/html/index.html
